### PR TITLE
Don't cache bad image information

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jrochkind** [comment]
Can you provide more info here on what goes wrong without this, so I (or other users) can recognize it if it happens to me, and/or monkey-patch solution while waiting for a release that includes this? Thanks!

**Comment by jcoyne** [comment]
If the image was retrieved prior to characterization it would cache the nil height and width. Openseadragon says invalid image information then. This is already released

**Comment by jrochkind** [comment]
Awesome, thanks. 

I'm used to being able to see what release a commit is in by looking at the github commit page and seeing what tags it's included in. But https://github.com/curationexperts/riiif/commit/471325ba1abfb27fc82dc6a345d7eb290c9ada02 lists none. Odd.

**Comment by jcoyne** [comment]
I think that commit got rebased into https://github.com/curationexperts/riiif/commit/7d064717d5205446ca0d4f435689350092d06e45

**Comment by mejackreed** [comment]
Just a follow up note, we found a breaking change in this commit in the way that `Riiif::Image#info` is accessed.

See:
https://github.com/sul-cidr/histonets/commit/90ff48b4d9e96d2df39eeee201dcb279af160615

**Pull request merged**
