### PR TITLE
ImageMagick: remove alpha channel from PDF thumbnails

### PR DESCRIPTION
**Pull request by dunn**
Will otherwise create black images in most cases.

### CODE REVIEW

**Comment by dunn** [comment]
We're getting this error: https://github.com/cbeer/engine_cart/issues/90, but I don't see any references to `.internal_test_gem` here.

**Comment by jcoyne** [comment]
@dunn that's using a really ancient version of engine_cart. Can you upgrade it?

**Comment by jcoyne** [comment]
@dunn looks like the upgrade is done in https://github.com/curationexperts/riiif/pull/121, just need someone to merge.

**Comment by jcoyne** [comment]
@dunn Jack merged that other PR, so can you rebase this?

**Comment by dunn** [comment]
I had to unpin bundler in order to test locally, but I can remove that commit if there's a reason to keep it at 1.x.

**Pull request merged**
