### PR TITLE
akubra resolver

### PR DESCRIPTION
**Pull request by yulgit1**
add to riiif.initializer.rb:

Riiif::Image.file_resolver = Riiif::AkubraSystemFileResolver

Riiif::AkubraSystemFileResolver.pathroot = <fedora /data datastream path>
Riiif::AkubraSystemFileResolver.imagetype = "jp2"
Riiif::AkubraSystemFileResolver.akubraconfig = [[0,2],[2,2],[4,1]]

[[0,2],[2,2],[4,1]] = ##/##/#

### CODE REVIEW

**Comment by jcoyne** [comment]
@yulgit1 would you mind rebasing this? Then I can merge it.

**Comment by yulgit1** [comment]
@jcoyne rebased.

**Comment by jcoyne** [comment]
@yulgit1 Okay, now AkubraSystemFileResolver needs to be changed into a class to follow the changes in https://github.com/curationexperts/riiif/commit/7edf149f8ca59c24d859d78024eb1e2b3c0b6c53 It should also have at least one test.

**Comment by yulgit1** [comment]
@jcoyne, ok made those changes and added a test

**Pull request merged**
